version: "3"
services:
  wincore11:
    image: dockurr/windows
    container_name: core11
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    environment:
      VERSION: "core11"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "16G"
    volumes:
      - ./storage:/storage
      - ./shared:/shared
    ports:
      - 80:8000
      - 443:4443
    # network_mode: "bridge"
